const LEGACY_KEY='xqn_admin_simple_contents_v1'
const LEGACY_METHOD_KEY='xqn_admin_problem_methods_v2'
const MIGRATION_KEY='xqn_admin_database_migrated_v1'
const $=selector=>document.querySelector(selector)
const clone=value=>JSON.parse(JSON.stringify(value))
const lines=value=>(value||'').split(/[\n,，;；]+/).map(item=>item.trim()).filter(Boolean)
const esc=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]))
const load=key=>{try{const value=JSON.parse(localStorage.getItem(key)||'[]');return Array.isArray(value)?value:[]}catch{return[]}}
const form=$('#content-form'),listNode=$('#content-list'),editorLayer=$('#editor-layer')
let contents=[],columns=[],editing=null,editingColumn=null,dirty=false,toastTimer=null,csrfToken='',needsSetup=false,currentView='methods',contentFilter='skill',sourceCandidates=[]
const BANNED_WORDS=['治疗','根治','治愈','疗效','诊断','处方','患者','治好了','疾病调理','包治','药到病除','立刻见效','永不复发']
const BODY_AREAS=[
['head','头面部','头 面部'],['eye','眼周','眼睛'],['ear','耳部','耳朵'],['nose','鼻部','鼻子'],['mouth','口唇周围','嘴 口周'],['cheek','面颊','脸颊'],['forehead','额部','额头'],['temple','颞部','太阳穴'],['jaw','下颌部','下巴'],['occiput','头后部','后脑'],
['neck','颈部','脖子'],['shoulder','肩部','肩膀'],['chest','胸部','胸前'],['upper-back','上背部','肩胛'],['abdomen','腹部','肚子 肚脐'],['lower-back','下背部','腰 腰部 腰骶 后腰'],['pelvis','下腹与腹股沟','下腹 小腹'],['buttocks','臀部','屁股'],['upper-arm','上臂','大臂'],['elbow','肘部','胳膊肘'],['forearm','前臂','小臂'],['hand','手部','手腕 手掌 手指'],['thigh','大腿',''],['knee','膝部','膝盖'],['lower-leg','小腿','腿肚'],['foot','足部','脚 足底 脚踝'],
['breast','乳房','乳腺区域'],['nipple-areola','乳头及乳晕','乳头 乳晕'],['vulva','外阴',''],['penis','阴茎',''],['scrotum','阴囊',''],['perineum','会阴',''],['anus','肛门及肛周','肛门 肛周'],['whole','全身','浑身']
].map(([id,name,aliases])=>({id,name,aliases}))
const LEGACY_AREA_MAP={'腰部':'lower-back','腰骶部':'lower-back','后腰':'lower-back','腰':'lower-back','肚子':'abdomen','腹部':'abdomen','足底':'foot','脚':'foot','头部':'head','头面部':'head','颈部':'neck','肩部':'shoulder','全身':'whole'}

function makeId(){return 'CNT-'+Date.now().toString(36).toUpperCase()+'-'+Math.random().toString(36).slice(2,5).toUpperCase()}
function blank(){return{id:makeId(),type:'skill',title:'',summary:'',keywords:'',bodyAreaIds:[],methodName:'',methodType:'acupoint',actionType:'',materials:'',actionParameters:'',audience:'',timing:'',contentHtml:'',usageScope:'',notices:'',outsideScope:'',helpConditions:'',casesHtml:'',columnId:'',columnName:'',issueNumber:'',topics:'',coverImage:'',editorNote:'',sourceKind:'xiaoqingnang',sourceArticleId:'',reviewStatus:'',removedPromotions:[],reviewFlags:[],sourceTitle:'',sourceAuthor:'',sourcePlatform:'',sourceUrl:'',sourceText:'',sourceNotes:'',pointLinks:[],problemLinks:[],status:'draft',updatedAt:Date.now()}}
function legacyMethodHtml(item){if(item.methodContentHtml)return item.methodContentHtml;const parts=[];if(item.methodLocation)parts.push(`<h3>准确位置</h3><p>${esc(item.methodLocation)}</p>`);(item.steps||[]).forEach((step,index)=>{parts.push(`<h3>第 ${index+1} 步 · ${esc(step.title||'')}</h3><p>${esc([step.instruction,step.intensity&&`力度：${step.intensity}`,step.duration&&`时间：${step.duration} 秒`,step.count&&`次数：${step.count}`,step.frequency&&`频率：${step.frequency}`].filter(Boolean).join('\n')).replace(/\n/g,'<br>')}</p>`);if(step.mediaUrl){const tag=/\.(mp4|mov|webm)(\?|$)/i.test(step.mediaUrl)?`<video src="${esc(step.mediaUrl)}" controls></video>`:`<img src="${esc(step.mediaUrl)}" alt="${esc(step.mediaAlt||'方法示意')}" />`;parts.push(tag)}});return parts.join('')}
function legacyCasesHtml(item){if(item.casesHtml)return item.casesHtml;return(item.cases||[]).map((value,index)=>`<h3>案例 ${index+1}</h3>${value.background?`<p><strong>情况：</strong>${esc(value.background)}</p>`:''}${value.methodUsed?`<p><strong>做法：</strong>${esc(value.methodUsed)}</p>`:''}${value.duration?`<p><strong>时间：</strong>${esc(value.duration)}</p>`:''}${value.subjectiveRecord?`<p><strong>记录：</strong>${esc(value.subjectiveRecord)}</p>`:''}${value.limitations?`<p><strong>局限：</strong>${esc(value.limitations)}</p>`:''}${value.sourceLocator?`<p><strong>出处：</strong>${esc(value.sourceLocator)}</p>`:''}`).join('')}
function normalizeAreaIds(item){const raw=Array.isArray(item.bodyAreaIds)?item.bodyAreaIds:[item.bodyArea].filter(Boolean);return[...new Set(raw.map(value=>BODY_AREAS.some(area=>area.id===value)?value:LEGACY_AREA_MAP[value]||BODY_AREAS.find(area=>area.name===value)?.id||'').filter(Boolean))]}
function normalize(item){const base=blank(),value={...base,...item,id:item.id||base.id,type:item.type==='article'?'article':'skill',title:item.title||'',summary:item.summary||'',keywords:item.keywords||'',bodyAreaIds:normalizeAreaIds(item),methodName:item.methodName||item.title||'',methodType:item.methodType||'acupoint',actionType:item.actionType||'',materials:item.materials||'',actionParameters:item.actionParameters||'',audience:item.audience||'',timing:item.timing||'',contentHtml:item.contentHtml||legacyMethodHtml(item),usageScope:item.usageScope||'',notices:item.notices||item.startNotes||'',outsideScope:item.outsideScope||'',helpConditions:item.helpConditions||'',casesHtml:legacyCasesHtml(item),columnId:item.columnId||'',columnName:item.columnName||'',issueNumber:item.issueNumber||'',topics:item.topics||'',coverImage:item.coverImage||'',editorNote:item.editorNote||'',sourceKind:item.sourceKind||'xiaoqingnang',sourceArticleId:item.sourceArticleId||'',reviewStatus:item.reviewStatus||'',removedPromotions:item.removedPromotions||[],reviewFlags:item.reviewFlags||[],sourceTitle:item.sourceTitle||'',sourceAuthor:item.sourceAuthor||'',sourcePlatform:item.sourcePlatform||'',sourceUrl:item.sourceUrl||'',sourceText:item.sourceText||'',sourceNotes:item.sourceNotes||'',pointLinks:item.pointLinks||[],problemLinks:item.problemLinks||[],status:item.status||'draft',updatedAt:item.updatedAt||Date.now(),publishedAt:item.publishedAt,version:item.version||1};return XqnCatalogs.normalizeLinks(value)}
async function api(path,options={}){const headers={...(options.headers||{})};if(options.body&&!headers['Content-Type'])headers['Content-Type']='application/json';if(options.method&&options.method!=='GET')headers['X-CSRF-Token']=csrfToken;const response=await fetch(path,{credentials:'same-origin',...options,headers});const result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(result.error||'请求失败');return result}
async function migrateLegacy(){if(contents.length||localStorage.getItem(MIGRATION_KEY))return;const legacy=[...load(LEGACY_METHOD_KEY),...load(LEGACY_KEY)];for(const item of legacy){await api('/api/admin/contents',{method:'POST',body:JSON.stringify({content:normalize(item)})})}localStorage.setItem(MIGRATION_KEY,'1');if(legacy.length)toast(`已将 ${legacy.length} 条本地草稿迁入数据库`)}
async function loadContents(){const result=await api('/api/admin/contents');contents=(result.contents||[]).map(normalize);await migrateLegacy();if(!contents.length&&localStorage.getItem(MIGRATION_KEY)){const refreshed=await api('/api/admin/contents');contents=(refreshed.contents||[]).map(normalize)}renderList();renderPendingImported();loadArticleSourceStatus()}
async function loadArticleSourceStatus(){
  // 当前本地服务未提供来源统计接口，直接从已加载内容计算，避免顶部出现 undefined。
  const imported=contents.filter(item=>item.type==='article'&&item.sourceKind==='zibingziyi'&&item.status!=='archived').length
  const review=contents.filter(item=>item.type==='article'&&item.sourceKind==='zibingziyi'&&item.reviewFlags&&item.reviewFlags.length).length
  const published=contents.filter(item=>item.type==='article'&&item.sourceKind==='zibingziyi'&&item.status==='published').length
  const node=$('#article-source-status')
  if(node)node.textContent=`自病自医：${imported} 篇已导入 · ${review} 篇商业复核 · ${published} 篇已发布`
}
async function loadCandidates(){const query=new URLSearchParams({status:$('#candidate-status').value,suggestedType:$('#candidate-type').value,q:$('#candidate-search').value.trim()});try{const result=await api('/api/admin/article-sources/zibingziyi/candidates?'+query.toString());sourceCandidates=result.candidates||[];renderCandidates();renderPendingImported()}catch(error){toast(error.message||'候选读取失败')}}
function renderCandidates(){const node=$('#candidate-list');$('#candidate-list-summary').textContent=`${sourceCandidates.length} 条`;$('#candidate-selection-count').textContent=`已选 ${sourceCandidates.filter(item=>item.screening_status==='selected').length} 篇`;if(!sourceCandidates.length){node.innerHTML='<div class="empty"><div><strong>没有符合条件的候选</strong><span>先点击“扫描候选”，或调整筛选条件。</span></div></div>';return}node.innerHTML=sourceCandidates.map(item=>{const flags=Array.isArray(item.screening_flags)?item.screening_flags:[],kind={article:'信息文集',problem:'可能是问题',skill:'可能是方法'}[item.suggested_type]||'待判断';return`<article class="candidate-row"><div class="candidate-main"><strong>${esc(item.title||'未命名文章')}</strong><span>${esc(item.summary||'暂无摘要')}</span><small>${esc(item.category||'未分类')} · 来源编号 ${esc(item.external_id)}</small></div><div class="candidate-tags"><b>${kind}</b>${flags.map(flag=>`<em>${esc(flag)}</em>`).join('')}</div><div class="candidate-actions"><button type="button" data-candidate-status="selected" data-candidate-id="${esc(item.external_id)}" ${item.screening_status==='selected'?'disabled':''}>${item.screening_status==='selected'?'已选中':'选中'}</button><button type="button" class="muted-action" data-candidate-status="ignored" data-candidate-id="${esc(item.external_id)}">忽略</button></div></article>`}).join('')}
function renderPendingImported(){const node=$('#candidate-list');if(!node)return;const values=contents.filter(item=>item.type==='article'&&item.sourceKind==='zibingziyi'&&item.status!=='published'&&item.status!=='archived').sort((a,b)=>b.updatedAt-a.updatedAt);if(!values.length)return;const rows=values.map(item=>`<article class="candidate-row imported-pending-row"><div class="candidate-main"><strong>${esc(item.title||'未命名文章')}</strong><span>${esc(item.summary||'已抓取正文，等待人工审核')}</span><small>已抓取正文 · ${item.reviewStatus==='reviewed'?'待发布':'待清理审核'}</small></div><div class="candidate-tags"><b>${item.reviewStatus==='reviewed'?'待发布':'待审核'}</b></div><div class="candidate-actions"><button type="button" data-pending-edit-id="${esc(item.id)}">处理</button></div></article>`).join('');const empty=node.querySelector('.empty');if(empty)empty.remove();node.insertAdjacentHTML('afterbegin',rows);const count=Number((document.querySelector('#candidate-list-summary')?.textContent||'0').match(/\d+/)?.[0]||0);$('#candidate-list-summary').textContent=`${count+values.length} 条`}
async function loadColumns(){const result=await api('/api/admin/columns');columns=result.columns||[];renderColumns();const select=$('#article-column');if(select)select.innerHTML='<option value="">未归入专栏</option>'+columns.filter(value=>value.status!=='hidden').map(value=>`<option value="${esc(value.id)}">${esc(value.name)}</option>`).join('')}
function renderColumns(){$('#count-columns').textContent=columns.length;$('#column-list-summary').textContent=`${columns.length} 个`;$('#column-admin-list').innerHTML=columns.map(value=>`<article class="column-admin-row"><i style="background:${esc(value.color)}"></i><div><strong>${esc(value.name)}</strong><span>${esc(value.description||'还没有介绍')}</span></div><b>${value.status==='hidden'?'已隐藏':'前台显示'}</b><em>顺序 ${Number(value.sort_order)||0}</em><button data-column-id="${esc(value.id)}">设置</button></article>`).join('')||'<div class="empty"><div><strong>还没有专栏</strong><span>新建后即可给文章选择。</span></div></div>'}
function toast(message){const node=$('#toast');node.textContent=message;node.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>node.classList.remove('show'),1800)}

function checksFor(item){
  const contentText=String(item.contentHtml||'').replace(/<[^>]*>/g,'').replace(/&nbsp;/g,' ').trim()
  const casesText=String(item.casesHtml||'').replace(/<[^>]*>/g,'').replace(/&nbsp;/g,' ').trim()
  const publicText=[item.title,item.summary,contentText,item.usageScope,item.notices,item.outsideScope,item.helpConditions,casesText].join(' ')
  const banned=item.type==='skill'?BANNED_WORDS.filter(word=>publicText.includes(word)):[]
  const checks=[['基本信息',!!item.title.trim(),'填写标题'],[item.type==='article'?'文章正文':'方法图文',!!contentText,'填写用户最终看到的图文内容'],['资料来源',!!item.sourceTitle.trim()&&!!item.sourceText.trim(),'填写资料标题和直接依据'],['公开用语',banned.length===0,banned.length?`需调整：${banned.join('、')}`:'公开文案未发现风险词']]
  if(item.type==='skill')checks.push(['风险边界',lines(item.outsideScope).length>0&&lines(item.helpConditions).length>0,'填写不适用情况和停止条件'])
  if(item.type==='skill')checks.splice(1,0,['标准位置',item.bodyAreaIds.length>0,'至少选择一个标准身体位置'])
  if(item.type==='skill')checks.splice(2,0,['方法信息',!!item.methodName.trim()&&!!item.methodType&&!!item.materials.trim(),'补齐方法名称、类型和工具'],['使用范围',lines(item.usageScope).length>0,'填写日常使用范围'])
  return checks.map(([label,done,hint])=>({label,done,hint}))
}
function completion(item){const checks=checksFor(item),done=checks.filter(value=>value.done).length;return{checks,done,total:checks.length,percent:Math.round(done/checks.length*100)}}
function renderList(){const query=$('#search-input').value.trim().toLowerCase();const reviewFilter=$('#article-review-filter')?.value||'all';const rows=contents.filter(item=>item.type===contentFilter&&item.status!=='archived'&&(!query||[item.title,item.summary,item.keywords,item.methodName,item.columnName,item.topics].join(' ').toLowerCase().includes(query))&&(contentFilter!=='article'||reviewFilter==='all'||(reviewFilter==='commercial'&&item.reviewFlags&&item.reviewFlags.length)||(reviewFilter==='published'&&item.status==='published')||(reviewFilter==='draft'&&item.status!=='published'))).sort((a,b)=>b.updatedAt-a.updatedAt);const articleCount=contents.filter(item=>item.type==='article'&&item.status!=='archived').length;const reviewCount=contents.filter(item=>item.type==='article'&&item.sourceKind==='zibingziyi'&&item.reviewFlags&&item.reviewFlags.length).length;$('#count-articles').textContent=articleCount;$('#count-methods').textContent=contents.filter(item=>item.type==='skill'&&item.status!=='archived').length;$('#list-title').textContent=contentFilter==='article'?'全部文章':'养护方法';$('#list-summary').textContent=contentFilter==='article'?`${rows.length} 条 · 总商业复核 ${reviewCount} 篇`:`${rows.length} 条`;if(!rows.length){listNode.innerHTML=`<div class="empty"><div><strong>没有符合筛选条件的文章</strong><span>请切换上方筛选条件或修改搜索词。</span></div></div>`;return}listNode.innerHTML=rows.map(item=>{const state=completion(item),labels={published:'已发布',archived:'已删除',withdrawn:'已撤回',ready:'可进入审核',draft:'草稿未完成'},needsReview=item.type==='article'&&item.sourceKind==='zibingziyi'&&item.reviewStatus!=='reviewed',label=needsReview?'待清理复核':item.status==='published'&&state.percent<100?'需整改':labels[item.status]||(state.percent===100?'可进入审核':'草稿未完成'),ready=!needsReview&&((item.status==='published'&&state.percent===100)||item.status==='ready'),kind=item.type==='article'?'文章':'方法',source=item.type==='article'?(item.sourceKind==='zibingziyi'?'自病自医':'小青囊原创'):'小青囊',flag=item.reviewFlags&&item.reviewFlags.length?' · 商业待核':'';return`<article class="content-row"><div class="content-icon ${item.type}">${kind.slice(0,1)}</div><div class="content-name"><strong>${esc(item.title||'未命名内容')}</strong><span>${esc(item.type==='article'?(item.columnName||'未归入专栏'):item.methodName||'还没有填写方法')}</span></div><div class="content-type">${esc(source)} · ${kind}${flag}</div><div class="progress-cell"><div class="progress-track"><i style="width:${state.percent}%"></i></div><span>${state.percent}%</span></div><div><span class="status ${ready?'ready':''}">${label}</span></div><button class="edit-button" data-edit-id="${item.id}">编辑</button></article>`}).join('')}

const baseRenderList=renderList
renderList=()=>{const backup=contents;if(contentFilter==='article')contents=backup.filter(item=>item.status==='published'||item.type!=='article'||item.sourceKind!=='zibingziyi');try{baseRenderList()}finally{contents=backup}}
const fields=['title','summary','keywords','methodName','methodType','actionType','materials','actionParameters','audience','timing','usageScope','notices','outsideScope','helpConditions','columnId','issueNumber','topics','coverImage','editorNote','sourceTitle','sourceAuthor','sourcePlatform','sourceUrl','sourceText','sourceNotes']
function fillForm(item){fields.forEach(name=>{form.elements[name].value=item[name]??''});$('#method-content').innerHTML=item.contentHtml||'';$('#case-content').innerHTML=item.casesHtml||'';renderAreaPicker();applyContentType();XqnCatalogs.renderRelations()}
function readForm(){if(!editing)return;fields.forEach(name=>{editing[name]=form.elements[name].value});editing.columnName=columns.find(value=>value.id===editing.columnId)?.name||'';editing.contentHtml=$('#method-content').innerHTML.trim();editing.casesHtml=editing.type==='skill'?$('#case-content').innerHTML.trim():''}
function applyContentType(){if(!editing)return;const isMethod=editing.type==='skill';$('#content-type-section').hidden=true;document.querySelectorAll('[data-method-only]').forEach(node=>node.hidden=!isMethod);document.querySelectorAll('[data-article-only]').forEach(node=>node.hidden=isMethod);$('#editor-kind').textContent=isMethod?'养护方法编辑':'青囊文集 · 文章编辑';$('#content-section-title').textContent=isMethod?'方法内容':'文章正文与排版';$('#content-section-copy').textContent=isMethod?'只处理可安全尝试的方法内容。':'按自病自医的阅读规范整理：标题、摘要、正文层级、图片与视频保持清晰节奏。';$('#boundary-title').textContent=isMethod?'风险边界':'阅读提示（可选）';$('#boundary-copy').textContent=isMethod?'明确不适用情况和必须停止的信号。':'需要时填写阅读背景或提醒，留空不会显示。';$('#boundary-label').innerHTML=isMethod?'不适用情况 <b>*</b>':'阅读提示';$('#rich-content-label').innerHTML=(isMethod?'方法图文':'文章正文')+' <b>*</b>';$('#method-content').classList.toggle('article-preview',!isMethod)}
function renderAreaPicker(){if(!editing)return;const term=$('#body-area-search').value.trim().toLowerCase(),selected=new Set(editing.bodyAreaIds);$('#body-area-selected').innerHTML=editing.bodyAreaIds.length?editing.bodyAreaIds.map(id=>{const area=BODY_AREAS.find(value=>value.id===id);return area?`<button type="button" data-remove-area="${area.id}">${esc(area.name)} ×</button>`:''}).join(''):'<span>尚未选择位置</span>';const values=BODY_AREAS.filter(area=>!term||[area.name,area.aliases].join(' ').toLowerCase().includes(term));$('#body-area-options').innerHTML=values.map(area=>`<button type="button" class="${selected.has(area.id)?'selected':''}" data-area-id="${area.id}"><i>${selected.has(area.id)?'✓':'＋'}</i>${esc(area.name)}</button>`).join('')}
function renderChecks(){readForm();const state=completion(editing);$('#completion-number').textContent=state.percent+'%';$('#check-list').innerHTML=state.checks.map(item=>`<div class="check-item ${item.done?'done':''}"><i>${item.done?'✓':'!'}</i><strong>${esc(item.label)}</strong><span>${item.done?'已完成':esc(item.hint)}</span></div>`).join('')}
async function openEditor(item){try{const result=await api(`/api/admin/contents/${encodeURIComponent(item.id)}`);item=result.content||item}catch(error){if(item.id&&!item.id.startsWith('CNT-')){toast(error.message||'正文读取失败');return}}editing=normalize(clone(item));dirty=false;$('#editor-title').textContent=editing.title||'新建资料';$('#withdraw-content').hidden=editing.status!=='published';$('#archive-content').hidden=!contents.some(value=>value.id===editing.id)||editing.status==='archived';fillForm(editing);renderChecks();editorLayer.hidden=false}
function closeEditor(force=false){if(!force&&dirty&&!confirm('还有未保存的修改，确定关闭吗？'))return;editorLayer.hidden=true;editing=null;dirty=false}
async function persistEditing(){readForm();const result=await api('/api/admin/contents',{method:'POST',body:JSON.stringify({content:clone(editing)})});editing=normalize(result.content);dirty=false;await loadContents();return result}
async function publishEditing(){readForm();const state=completion(editing);if(state.percent!==100){renderChecks();$('.check-section').scrollIntoView({behavior:'smooth'});toast(`还有 ${state.total-state.done} 项需要补充`);return}const imported=editing.type==='article'&&editing.sourceKind==='zibingziyi';const message=imported?'确认已逐段核对正文、图片、二维码和自动清理记录，文章中不再包含商业推广，并发布到文集？':editing.type==='article'?'确认已核对文章正文与资料来源，并发布到文集？':'确认已人工核对资料来源、方法参数与风险边界，并发布到前台？';if(!confirm(message))return;if(imported)editing.reviewStatus='reviewed';const button=$('#publish-content');button.disabled=true;button.textContent='正在发布…';try{await persistEditing();const result=await api(`/api/admin/contents/${encodeURIComponent(editing.id)}/publish`,{method:'POST'});editing=result.content;closeEditor(true);await loadContents();toast('已发布，前台现在可以搜索')}catch(error){toast(error.message||'发布失败')}finally{button.disabled=false;button.textContent='保存并发布'}}

async function boot(){try{const result=await api('/api/admin/bootstrap');needsSetup=result.needsSetup;csrfToken=result.csrfToken||'';if(result.authenticated){$('#auth-layer').hidden=true;$('#admin-user').textContent=result.username;await XqnCatalogs.load();await loadColumns();await loadContents()}else{showAuth()}}catch(error){showAuth(error.message)}}
function showAuth(message=''){const layer=$('#auth-layer');layer.hidden=false;$('#auth-eyebrow').textContent=needsSetup?'首次使用':'后台登录';$('#auth-title').textContent=needsSetup?'创建管理员':'登录小青囊';$('#auth-copy').textContent=needsSetup?'此账号将管理内容和发布权限。':'内容只允许管理员查看和发布。';$('#confirm-field').hidden=!needsSetup;$('#auth-submit').textContent=needsSetup?'创建并进入后台':'登录';$('#auth-error').textContent=message}
XqnCatalogs.configure({api,toast,bodyAreas:BODY_AREAS,getEditing:()=>editing,getCsrf:()=>csrfToken,getMethods:()=>contents.filter(item=>item.type==='skill'&&item.status!=='archived'),refreshContents:loadContents})
boot()
document.querySelectorAll('[data-admin-view]').forEach(button=>{button.onclick=()=>switchView(button.dataset.adminView)})
const anthologySection=document.querySelector('.nav-section-anthology')
anthologySection?.addEventListener('toggle',()=>{
  if(['articles','columns','candidates'].includes(currentView))$('#anthology-nav').hidden=!anthologySection.open
})
$('#anthology-entry').onclick=event=>{
  if(!anthologySection)return
  if(currentView!=='articles'){
    event.preventDefault()
    anthologySection.open=true
    switchView('articles')
  }
}
switchView(currentView)
function switchView(view){
  currentView=view
  const isAnthology=['articles','columns','candidates'].includes(view)
  const isContent=['articles','methods'].includes(view)
  const labels={methods:'基础数据库 / 方法库',problems:'基础数据库 / 问题库',points:'基础数据库 / 穴位库',articles:'青囊文集 / 文章管理',columns:'青囊文集 / 专栏设计',candidates:'青囊文集 / 来源同步'}
  $('#breadcrumb').innerHTML=(labels[view]||'小青囊后台').replace(' / ',' <span>/</span> ')
  document.querySelectorAll('[data-admin-view]').forEach(node=>node.classList.toggle('active',node.dataset.adminView===view))
  $('#anthology-entry').classList.toggle('active',isAnthology)
  $('#anthology-entry').setAttribute('aria-current',isAnthology?'page':'false')
  $('#anthology-nav').hidden=!isAnthology
  $('#contents-main').hidden=!isContent
  $('#columns-main').hidden=view!=='columns'
  $('#candidates-main').hidden=view!=='candidates'
  $('#problems-main').hidden=view!=='problems'
  $('#points-main').hidden=view!=='points'
  $('#content-search').hidden=!isContent
  $('#article-review-filter').hidden=view!=='articles'
  $('#create-content').hidden=!['articles','methods','problems','points'].includes(view)
  $('#word-import').hidden=view!=='articles'
  if(isContent){
    contentFilter=view==='methods'?'skill':'article'
    const article=contentFilter==='article'
    $('#content-page-title').textContent=article?'文章管理':'方法库'
    $('#content-page-copy').textContent=article?'管理文集文章、图文排版、专栏归属与发布。':'每个方法只制作一次，再关联问题与穴位。'
    $('#create-content').textContent=article?'＋ 新建文章':'＋ 新建方法'
    renderList()
  }else if(view==='problems'){$('#create-content').textContent='＋ 新建问题'}
  else if(view==='points'){$('#create-content').textContent='＋ 新建穴位'}
  if(view==='columns')loadColumns()
  if(view==='candidates')loadCandidates()
}
$('#create-column').onclick=()=>openColumn({id:'',name:'',description:'',color:'#DCEEDB',sort_order:columns.length,status:'visible'})
$('#column-admin-list').onclick=event=>{const button=event.target.closest('[data-column-id]');if(button)openColumn(columns.find(value=>value.id===button.dataset.columnId))}
function openColumn(value){editingColumn={...value};$('#delete-column').hidden=!value.id;const form=$('#column-form');form.elements.name.value=value.name||'';form.elements.description.value=value.description||'';form.elements.color.value=value.color||'#DCEEDB';form.elements.sort_order.value=value.sort_order||0;form.elements.status.value=value.status||'visible';$('#column-editor-title').textContent=value.id?'设置专栏':'新建专栏';$('#column-editor-layer').hidden=false}
$('#cancel-column').onclick=()=>{$('#column-editor-layer').hidden=true;editingColumn=null}
$('#delete-column').onclick=async()=>{
  if(!editingColumn?.id)return
  if(!confirm(`确认删除“${editingColumn.name}”？专栏中的文章不会删除，将改为未归入专栏。`))return
  const button=$('#delete-column');button.disabled=true
  try{
    await api(`/api/admin/columns/${encodeURIComponent(editingColumn.id)}/delete`,{method:'POST'})
    $('#column-editor-layer').hidden=true;editingColumn=null
    await loadColumns();await loadContents();toast('专栏已删除，文章已保留')
  }catch(error){toast(error.message)}finally{button.disabled=false}
}
$('#column-form').onsubmit=async event=>{event.preventDefault();const data=new FormData(event.currentTarget),column={...editingColumn,name:String(data.get('name')||''),description:String(data.get('description')||''),color:String(data.get('color')||'#DCEEDB'),sort_order:Number(data.get('sort_order'))||0,status:String(data.get('status')||'visible')};try{await api('/api/admin/columns',{method:'POST',body:JSON.stringify({column})});$('#column-editor-layer').hidden=true;await loadColumns();toast('专栏设置已保存')}catch(error){toast(error.message)}}
$('#search-input').oninput=renderList
$('#article-review-filter').onchange=renderList
$('#create-content').onclick=()=>{if(currentView==='problems')return XqnCatalogs.openProblem();if(currentView==='points')return XqnCatalogs.openPoint();const item=blank();item.type=contentFilter;openEditor(item)}
$('#word-import-input').onchange=async event=>{const input=event.target,file=input.files?.[0];if(!file)return;input.disabled=true;toast('正在解析 Word…');try{const response=await fetch('/api/admin/import-docx?name='+encodeURIComponent(file.name),{method:'POST',credentials:'same-origin',headers:{'Content-Type':file.type||'application/vnd.openxmlformats-officedocument.wordprocessingml.document','X-CSRF-Token':csrfToken},body:file});const result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(result.error||'Word 导入失败');openEditor(result.content);toast('已读取 Word，请校对后保存或发布')}catch(error){toast(error.message)}finally{input.disabled=false;input.value=''}}
$('#sync-zibingziyi').onclick=async()=>{const button=$('#sync-zibingziyi');if(!confirm('开始从自病自医读取文章？新文章只会进入草稿，自动清理后仍需人工复核才可发布。'))return;button.disabled=true;button.textContent='正在同步…';try{const result=await api('/api/admin/article-sources/zibingziyi/sync',{method:'POST'});await loadColumns();await loadContents();toast(`同步完成：新增 ${result.created}，更新 ${result.updated}，未变化 ${result.unchanged}`)}catch(error){toast(error.message||'同步失败，原有文章未改动')}finally{button.disabled=false;button.textContent='同步自病自医'}}
$('#scan-zibingziyi').onclick=async()=>{const button=$('#scan-zibingziyi');if(!confirm('只扫描自病自医文章目录并生成候选，不抓取正文、不修改现有内容，继续吗？'))return;button.disabled=true;button.textContent='扫描中…';try{const result=await api('/api/admin/article-sources/zibingziyi/scan',{method:'POST'});await loadArticleSourceStatus();toast(`扫描完成：${result.received} 篇，建议候选 ${result.candidates} 篇，疑似商业 ${result.promotionFlags} 篇`)}catch(error){toast(error.message||'扫描失败，现有内容未改动')}finally{button.disabled=false;button.textContent='扫描候选'}}
$('#candidate-search').oninput=()=>{clearTimeout(window.__candidateSearchTimer);window.__candidateSearchTimer=setTimeout(loadCandidates,250)}
$('#candidate-type').onchange=loadCandidates;$('#candidate-status').onchange=loadCandidates
$('#candidate-list').onclick=async event=>{const button=event.target.closest('[data-candidate-status]');if(!button)return;button.disabled=true;try{await api(`/api/admin/article-sources/zibingziyi/candidates/${encodeURIComponent(button.dataset.candidateId)}`,{method:'POST',body:JSON.stringify({status:button.dataset.candidateStatus})});await loadCandidates();await loadArticleSourceStatus();toast(button.dataset.candidateStatus==='selected'?'已加入导入队列':'已忽略')}catch(error){toast(error.message||'候选状态保存失败')}finally{button.disabled=false}}
$('#import-selected-candidates').onclick=async()=>{const button=$('#import-selected-candidates');if(!confirm('开始抓取已选文章正文吗？纯商业内容会跳过，夹杂商业内容会清理并标记人工复核。'))return;button.disabled=true;let total={created:0,updated:0,unchanged:0,flagged:0,skipped:0};try{for(;;){button.textContent=`正在抓取… 新增 ${total.created}`;const result=await api('/api/admin/article-sources/zibingziyi/import-selected?limit=100&offset=0',{method:'POST'});['created','updated','unchanged','flagged','skipped'].forEach(key=>{total[key]+=Number(result[key]||0)});if(!result.received)break}await loadContents();await loadCandidates();await loadArticleSourceStatus();toast(`完成：新增 ${total.created}，跳过商业 ${total.skipped}，待复核 ${total.flagged}`)}catch(error){toast(error.message||'抓取失败，已完成的批次保留')}finally{button.disabled=false;button.textContent='抓取已选正文'}}
listNode.onclick=event=>{const button=event.target.closest('[data-edit-id]');if(button){const item=contents.find(value=>value.id===button.dataset.editId);if(item)openEditor(item)}}
$('#candidate-list').addEventListener('click',event=>{const button=event.target.closest('[data-pending-edit-id]');if(button){const item=contents.find(value=>value.id===button.dataset.pendingEditId);if(item)openEditor(item)}})
$('#close-editor').onclick=()=>closeEditor();$('#cancel-edit').onclick=()=>closeEditor()
form.addEventListener('input',()=>{dirty=true;renderChecks()})
function bindRichToolbar(toolbarSelector,editorSelector){$(toolbarSelector).onclick=event=>{const button=event.target.closest('[data-command]');if(!button)return;event.preventDefault();$(editorSelector).focus();document.execCommand(button.dataset.command,false,button.dataset.value||null);dirty=true;renderChecks()}}
function bindRichUpload(inputSelector,editorSelector){$(inputSelector).onchange=async event=>{const picker=event.target,files=[...(picker.files||[])];if(!files.length)return;picker.disabled=true;let inserted=0;try{for(const file of files){const response=await fetch('/api/upload?name='+encodeURIComponent(file.name),{method:'POST',credentials:'same-origin',headers:{'Content-Type':file.type,'X-CSRF-Token':csrfToken},body:file});const result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(result.error||'素材保存失败');const caption=prompt(`请填写“${file.name}”准确表达的内容：`,file.name)||file.name;const html=file.type.startsWith('video/')?`<video src="${esc(result.url)}" controls></video><p class="media-caption">${esc(caption)}</p>`:`<img src="${esc(result.url)}" alt="${esc(caption)}"><p class="media-caption">${esc(caption)}</p>`;$(editorSelector).insertAdjacentHTML('beforeend',html);inserted++}dirty=true;renderChecks();toast(`已按顺序插入 ${inserted} 个素材`)}catch(error){toast(`${inserted?`已插入 ${inserted} 个；`:''}${error.message}`)}finally{picker.disabled=false;picker.value=''}}}
bindRichToolbar('#method-toolbar','#method-content')
bindRichToolbar('#case-toolbar','#case-content')
bindRichUpload('#method-media-upload','#method-content')
bindRichUpload('#case-media-upload','#case-content')
$('#check-content').onclick=()=>{renderChecks();$('.check-section').scrollIntoView({behavior:'smooth'});const state=completion(editing);toast(state.percent===100?'信息已完整，可以进入人工审核':`还有 ${state.total-state.done} 项需要补充`)}
$('#publish-content').onclick=publishEditing
$('#withdraw-content').onclick=async()=>{if(!editing||editing.status!=='published'||!confirm('撤回后，前台将立即不再显示这条资料。确认撤回？'))return;try{await api(`/api/admin/contents/${encodeURIComponent(editing.id)}/withdraw`,{method:'POST'});closeEditor(true);await loadContents();toast('已从前台撤回')}catch(error){toast(error.message)}}
$('#archive-content').onclick=async()=>{if(!editing||!confirm('确认删除这条资料？删除后将从后台列表和前台移除。'))return;try{await api(`/api/admin/contents/${encodeURIComponent(editing.id)}/archive`,{method:'POST'});closeEditor(true);await loadContents();toast('已删除')}catch(error){toast(error.message)}}
form.onsubmit=async event=>{event.preventDefault();try{await persistEditing();closeEditor(true);toast('草稿已保存')}catch(error){toast(error.message)}}
$('#auth-form').onsubmit=async event=>{event.preventDefault();const values=new FormData(event.currentTarget),username=String(values.get('username')||''),password=String(values.get('password')||'');if(needsSetup&&password!==String(values.get('confirmPassword')||'')){return showAuth('两次输入的密码不一致')}try{const result=await api(needsSetup?'/api/admin/setup':'/api/admin/login',{method:'POST',body:JSON.stringify({username,password})});csrfToken=result.csrfToken;$('#admin-user').textContent=result.username;$('#auth-layer').hidden=true;await XqnCatalogs.load();await loadContents()}catch(error){showAuth(error.message)}}
$('#logout-admin').onclick=async()=>{try{await api('/api/admin/logout',{method:'POST'});csrfToken='';contents=[];renderList();showAuth()}catch(error){toast(error.message)}}
if($('#export-data'))$('#export-data').onclick=()=>{window.location.href='/api/admin/export'}
if($('#show-logs'))$('#show-logs').onclick=async()=>{try{const result=await api('/api/admin/logs'),names={setup:'创建管理员',login:'登录',logout:'退出',save:'保存内容',publish:'发布内容',withdraw:'撤回内容',upload:'上传素材'};$('#logs-list').innerHTML=result.logs.length?result.logs.map(item=>`<div class="log-row"><strong>${esc(names[item.action]||item.action)}</strong><span>${esc(item.entity_id||item.entity_type)} · ${esc(item.username||'系统')}</span><time>${new Date(item.created_at).toLocaleString('zh-CN',{hour12:false})}</time></div>`).join(''):'<div class="logs-empty">还没有操作记录</div>';$('#logs-layer').hidden=false}catch(error){toast(error.message)}}
$('#close-logs').onclick=()=>{$('#logs-layer').hidden=true}
$('#body-area-search').oninput=renderAreaPicker
$('#body-area-options').onclick=event=>{const button=event.target.closest('[data-area-id]');if(!button||!editing)return;const id=button.dataset.areaId,index=editing.bodyAreaIds.indexOf(id);if(index>=0)editing.bodyAreaIds.splice(index,1);else editing.bodyAreaIds.push(id);dirty=true;renderAreaPicker();renderChecks()}
$('#body-area-selected').onclick=event=>{const button=event.target.closest('[data-remove-area]');if(!button||!editing)return;editing.bodyAreaIds=editing.bodyAreaIds.filter(id=>id!==button.dataset.removeArea);dirty=true;renderAreaPicker();renderChecks()}
function showPreview(){readForm();const isMethod=editing.type==='skill',sections=[];if(isMethod&&lines(editing.usageScope).length)sections.push(['使用范围',lines(editing.usageScope)]);if(isMethod&&lines(editing.notices).length)sections.push(['注意事项',lines(editing.notices)]);if(lines(editing.outsideScope).length||lines(editing.helpConditions).length)sections.push([isMethod?'风险边界':'阅读提示',[...lines(editing.outsideScope),...lines(editing.helpConditions)]]);$('#preview-title').textContent=editing.title||'未命名内容';$('#preview-body').innerHTML=`<div class="pv-tag">${isMethod?'养护方法':'青囊文集'}</div><h1>${esc(editing.title||'未命名内容')}</h1>${editing.summary?`<p class="pv-summary">${esc(editing.summary)}</p>`:''}<div class="pv-content">${editing.contentHtml||'<p>还没有正文</p>'}</div>${isMethod?XqnCatalogs.relationPreviewHtml(editing):''}${sections.map(([title,items])=>`<section><h2>${title}</h2>${items.map(item=>`<p>· ${esc(item)}</p>`).join('')}</section>`).join('')}${isMethod&&editing.casesHtml?`<section><h2>案例集</h2><p>以下均为个体经验，仅供参考，不代表普遍效果。</p>${editing.casesHtml}</section>`:''}`;$('#preview-layer').hidden=false}
$('#preview-content').onclick=showPreview
$('#close-preview').onclick=()=>{$('#preview-layer').hidden=true}
