'use client'

import Link from 'next/link'
import { useCallback, useEffect, useMemo, useState } from 'react'
import { useToast } from './ToastProvider'
import { adminRequest, errorMessage, formatDate, writeOptions, type AdminSection } from '@/src/lib/admin-client'
import { ConfirmDialog, Empty, ErrorNotice, Loading, PageHeading, Pagination, Status } from './admin/AdminUI'

const PAGE_SIZE=24
const labels:Record<AdminSection,string>={articles:'文章管理',methods:'方法库',problems:'问题库',points:'穴位库',columns:'专栏设计',review:'来源同步与审核',logs:'操作记录',backup:'导出备份',permissions:'管理员权限'}
const tableLabels:Record<string,string>={title:'标题',name:'名称',summary:'摘要',description:'说明',status:'状态',reviewStatus:'复核状态',updatedAt:'更新时间',createdAt:'时间',bodyAreaId:'标准部位',professionalLocation:'专业定位',count:'文章数',username:'操作人',action:'操作',entityType:'对象',entityId:'对象编号'}

function useAdminData(section:AdminSection,query:string,page:number){
  const [data,setData]=useState<any>({}); const [loading,setLoading]=useState(true); const [error,setError]=useState('')
  const load=useCallback(async()=>{setLoading(true);setError('');try{const encoded=query?`&q=${encodeURIComponent(query)}`:'';const endpoint=section==='articles'?`/api/admin/contents?type=article&page=${page}&pageSize=${PAGE_SIZE}${encoded}`:section==='methods'?`/api/admin/contents?type=skill&page=${page}&pageSize=${PAGE_SIZE}${encoded}`:section==='review'?`/api/admin/article-sources/zibingziyi?status=candidate&page=${page}&pageSize=${PAGE_SIZE}${query?`&q=${encodeURIComponent(query)}`:''}`:section==='columns'?'/api/admin/columns':section==='problems'?'/api/admin/problems':section==='points'?'/api/admin/points':section==='logs'?'/api/admin/logs':section==='permissions'?'/api/admin/users':'/api/admin/article-sources';const raw=await adminRequest<any>(endpoint);if(section==='review'){const candidates=(raw.candidates||[]).map((item:any)=>({...item,id:item.external_id,status:item.screening_status,reviewStatus:(item.screeningFlags||[]).join('、')||'未发现商业痕迹',updatedAt:item.scanned_at}));setData({...raw,contents:candidates,total:raw.total||0})}else setData(raw)}catch(e){setError(errorMessage(e))}finally{setLoading(false)}},[section,query,page])
  useEffect(()=>{load()},[load])
  return {data,loading,error,load}
}

export function AdminWorkspace({section}:{section:AdminSection}){
  const [query,setQuery]=useState('');const [input,setInput]=useState('');const [page,setPage]=useState(1);const {data,loading,error,load}=useAdminData(section,query,page);const {show}=useToast();const [csrf,setCsrf]=useState('');const [selected,setSelected]=useState<string[]>([]);const [pending,setPending]=useState<{id:string;verb:string;label:string}|null>(null);const [busy,setBusy]=useState(false)
  useEffect(()=>{adminRequest<any>('/api/admin/bootstrap').then(d=>setCsrf(d.user?.csrfToken||'')).catch(()=>{})},[])
  useEffect(()=>{setPage(1);setSelected([])},[section])
  const items=useMemo(()=>section==='articles'||section==='methods'||section==='review'?(data.contents||[]):section==='columns'?(data.columns||[]):section==='problems'?(data.problems||[]):section==='points'?(data.points||[]):section==='logs'?(data.logs||[]):section==='permissions'?(data.users||[]):[],[data,section])
  const total=Number(data.total||data.count||items.length||0);const paged=section==='articles'||section==='methods'||section==='review'
  const runContentAction=async()=>{if(!pending)return;setBusy(true);try{await adminRequest(`/api/admin/contents/${encodeURIComponent(pending.id)}/${pending.verb}`,writeOptions(csrf));show(`${pending.label}成功`,'success');setPending(null);await load()}catch(e){show(errorMessage(e),'error')}finally{setBusy(false)}}
  const sourceAction=async(action:string)=>{setBusy(true);try{if(action==='select'){await Promise.all(selected.map(id=>adminRequest('/api/admin/article-sources/zibingziyi',writeOptions(csrf,{action:'set-status',externalId:id,status:'selected'}))))}else{await adminRequest<any>('/api/admin/article-sources/zibingziyi',{...writeOptions(csrf,{action,ids:selected}),headers:{'Content-Type':'application/json','X-CSRF-Token':csrf}})}show(action==='select'?'已标记为待导入':'操作完成','success');setSelected([]);await load()}catch(e){show(errorMessage(e),'error')}finally{setBusy(false)}}
  const deleteColumn=async(id:string)=>{setBusy(true);try{await adminRequest(`/api/admin/columns/${encodeURIComponent(id)}/delete`,writeOptions(csrf));show('专栏已删除','success');await load()}catch(e){show(errorMessage(e),'error')}finally{setBusy(false)}}
  if(section==='backup')return <BackupPage/>
  if(section==='permissions')return <PermissionPanel data={data} csrf={csrf} onSaved={load}/>
  if(section==='review')return <ReviewPage data={data} items={items} loading={loading} error={error} query={input} onQueryChange={setInput} selected={selected} setSelected={setSelected} onSearch={()=>{setQuery(input.trim());setPage(1)}} onRetry={load} onSource={sourceAction} page={page} total={total} onPage={setPage} busy={busy}/>
  const description=section==='articles'?'只展示已发布和本地编辑稿；来自外部来源的待审核文章统一在「来源同步与审核」。':section==='methods'?'维护可以被用户搜索的养护方法，并关联问题、部位和穴位。':section==='columns'?'管理文章的专栏归属、颜色和展示顺序。':section==='problems'?'维护用户说法与方法之间的索引，不在这里重复编写方法正文。':section==='points'?'维护穴位的专业定位与经验取穴方式，供方法重复调用。':'查看最近的后台操作记录。'
  const create=section==='articles'?'新建文章':section==='methods'?'新建方法':section==='problems'?'新建问题':section==='points'?'新建穴位':''
  return <><PageHeading title={labels[section]} description={description} actions={create&&<Link href={`/admin/${section}/new`} className="admin-button">{create}</Link>}/><div className="admin-toolbar"><form className="admin-search" onSubmit={e=>{e.preventDefault();setQuery(input.trim());setPage(1)}}><input aria-label="搜索资料" value={input} onChange={e=>setInput(e.target.value)} placeholder={section==='columns'?'搜索专栏名称':'搜索标题、摘要或正文'}/><button className="admin-button secondary">搜索</button></form>{section==='articles'&&<DocxImport csrf={csrf} onImported={load}/>} {section==='columns'&&<ColumnCreate csrf={csrf} onSaved={load}/>}</div><div className="admin-panel">{error?<ErrorNotice message={error} retry={load}/>:loading?<Loading/>:items.length===0?<Empty filtered={Boolean(query)}/>:<><AdminTable items={items} section={section} onContentAction={(id,verb,label)=>setPending({id,verb,label})} onDelete={section==='columns'?deleteColumn:undefined}/>{paged&&<Pagination page={page} total={total} size={PAGE_SIZE} busy={loading} onChange={setPage}/>}</>}</div>{pending&&<ConfirmDialog title={`${pending.label}这条资料？`} description="操作会立即改变后台状态；已发布内容的公开状态会同步变化。" busy={busy} onCancel={()=>setPending(null)} onConfirm={runContentAction} label={pending.label}/>}</>
}

function AdminTable({items,section,onContentAction,onDelete,selected=[],setSelected}:{items:any[];section:AdminSection;onContentAction?:(id:string,verb:string,label:string)=>void;onDelete?:(id:string)=>void;selected?:string[];setSelected?:(v:string[])=>void}){return <div className="admin-table-wrap"><table className="admin-table"><thead><tr>{(section==='review')&&<th>选择</th>}{visibleColumns(section).map(c=><th key={c}>{tableLabels[c]||c}</th>)}{(section==='articles'||section==='methods'||section==='problems'||section==='points'||section==='columns'||section==='review')&&<th>操作</th>}</tr></thead><tbody>{items.map((item:any)=>{const id=item.id||item.entityId;const editSection=section==='articles'||section==='methods'||section==='problems'||section==='points';return <tr key={id}>{section==='review'&&<td><input type="checkbox" aria-label={`选择${item.title||id}`} checked={selected.includes(id)} onChange={e=>setSelected?.(e.target.checked?[...selected,id]:selected.filter(x=>x!==id))}/></td>}{visibleColumns(section).map(column=><td key={column}>{column==='title'||column==='name'?<><strong>{item[column]||'未命名'}</strong><small>{item.columnName||item.summary||item.description||''}</small></>:column==='status'||column==='reviewStatus'?<Status value={String(item[column]||'')}/>:column.endsWith('At')?formatDate(item[column]):String(item[column]??'—')}</td>)}{editSection&&<td><Link className="admin-button secondary" href={`/admin/${section}/${id}`}>编辑</Link>{(section==='articles'||section==='methods')&&<button className="admin-button secondary" onClick={()=>onContentAction?.(id,item.status==='published'?'withdraw':'publish',item.status==='published'?'撤回':'发布')}>{item.status==='published'?'撤回':'发布'}</button>}</td>}{section==='review'&&<td>{item.source_url?<a className="admin-button secondary" href={item.source_url} target="_blank" rel="noreferrer">查看来源</a>:<button className="admin-button secondary" onClick={()=>onContentAction?.(id,'select','标记待导入')}>标记待导入</button>}</td>}{section==='columns'&&<td><button className="admin-button secondary" onClick={()=>{if(window.confirm('删除后不可恢复，确定删除这个专栏吗？'))onDelete?.(id)}}>删除</button></td>}</tr>})}</tbody></table></div>}
function visibleColumns(section:AdminSection){if(section==='articles'||section==='methods')return ['title','summary','status','updatedAt'];if(section==='review')return ['title','status','reviewStatus','updatedAt'];if(section==='columns')return ['name','description','count','status'];if(section==='problems')return ['name','description','status'];if(section==='points')return ['name','bodyAreaId','professionalLocation','status'];return ['username','action','entityType','entityId','createdAt']}
function PageFrame({title,description,children}:{title:string;description:string;children:any}){return <><PageHeading title={title} description={description}/>{children}</>}
function ReviewPage({data,items,loading,error,query,onQueryChange,selected,setSelected,onSearch,onRetry,onSource,page,total,onPage,busy}:{data:any;items:any[];loading:boolean;error:string;query:string;onQueryChange:(v:string)=>void;selected:string[];setSelected:(v:string[])=>void;onSearch:()=>void;onRetry:()=>void;onSource:(a:string)=>void;page:number;total:number;onPage:(p:number)=>void;busy:boolean}){return <PageFrame title="来源同步与审核" description="扫描自病自医目录、查看商业复核状态，再把确认后的正文导入文章管理。"><div className="admin-toolbar"><button className="admin-button" disabled={busy} onClick={()=>onSource('scan')}>扫描候选</button><button className="admin-button secondary" disabled={busy} onClick={()=>onSource('sync')}>同步正文</button><button className="admin-button secondary" disabled={busy||!selected.length} onClick={()=>onSource('select')}>标记待导入（{selected.length}）</button><button className="admin-button secondary" disabled={busy||!selected.length} onClick={()=>onSource('import-selected')}>导入已选</button></div><div className="admin-stat">自病自医目录候选 {data.total||0} 篇 · 当前筛选 {items.length} 篇</div><form className="admin-search" onSubmit={e=>{e.preventDefault();onSearch()}}><input value={query} onChange={e=>onQueryChange(e.target.value)} placeholder="搜索待审核文章"/><button className="admin-button secondary">搜索</button></form><div className="admin-panel admin-review-table">{error?<ErrorNotice message={error} retry={onRetry}/>:loading?<Loading/>:items.length===0?<Empty filtered={Boolean(query)}/>:<><AdminTable items={items} section="review" selected={selected} setSelected={setSelected}/><Pagination page={page} total={total} size={PAGE_SIZE} onChange={onPage} busy={loading}/></>}</div></PageFrame>}
function BackupPage(){return <PageFrame title="导出备份" description="导出当前 SQLite 内容，供留档或迁移使用。"><div className="admin-panel"><h2>数据备份</h2><p className="reader-meta">导出不会修改线上数据，请下载后放在安全位置。</p><a className="admin-button" href="/api/admin/export">下载 JSON 备份</a></div></PageFrame>}
function ColumnCreate({csrf,onSaved}:{csrf:string;onSaved:()=>void}){const [name,setName]=useState('');return <form className="inline-create" onSubmit={async e=>{e.preventDefault();if(!name.trim())return;try{await adminRequest('/api/admin/columns',writeOptions(csrf,{name:name.trim()}));setName('');onSaved()}catch(error){alert(errorMessage(error))}}}><input aria-label="专栏名称" value={name} onChange={e=>setName(e.target.value)} placeholder="新专栏名称"/><button className="admin-button" type="submit">新建专栏</button></form>}
function DocxImport({csrf,onImported}:{csrf:string;onImported:()=>void}){const [busy,setBusy]=useState(false);return <label className="admin-button secondary file-button">{busy?'导入中…':'导入 Word'}<input type="file" accept=".docx,application/vnd.openxmlformats-officedocument.wordprocessingml.document" hidden disabled={busy} onChange={async e=>{const file=e.target.files?.[0];if(!file)return;setBusy(true);try{await adminRequest(`/api/admin/import-docx?name=${encodeURIComponent(file.name)}`,{method:'POST',headers:{'Content-Type':file.type||'application/vnd.openxmlformats-officedocument.wordprocessingml.document','X-CSRF-Token':csrf},body:await file.arrayBuffer()});alert('Word 已导入草稿');onImported()}catch(error){alert(errorMessage(error))}finally{setBusy(false);e.target.value=''}}}/></label>}
function PermissionPanel({data,csrf,onSaved}:{data:any;csrf:string;onSaved:()=>void}){const users=data.users||[];return <PageFrame title="管理员权限" description="超级管理员可以配置普通管理员可见的菜单和可执行的操作。"><div className="admin-panel"><div className="admin-stat">当前管理员 {users.length} 位</div>{users.map((u:any)=><PermissionRow key={u.id} user={u} csrf={csrf} onSaved={onSaved}/>)}</div></PageFrame>}
function PermissionRow({user,csrf,onSaved}:{user:any;csrf:string;onSaved:()=>void}){const [open,setOpen]=useState(false);const [values,setValues]=useState<string[]>(user.permissions||[]);const save=async()=>{try{await adminRequest('/api/admin/users',writeOptions(csrf,{userId:user.id,permissions:values}));setOpen(false);onSaved()}catch(error){alert(errorMessage(error))}};return <div className="permission-row"><div><strong>{user.username}</strong><small>{user.accountType==='super_admin'?'超级管理员':'普通管理员'}</small></div>{user.accountType!=='super_admin'&&<><button className="admin-button secondary" onClick={()=>setOpen(!open)}>{open?'收起':'配置权限'}</button>{open&&<div className="permission-picker">{(user.catalog||[]).map((p:any)=><label key={p.code}><input type="checkbox" checked={values.includes(p.code)} onChange={e=>setValues(e.target.checked?[...values,p.code]:values.filter(x=>x!==p.code))}/>{p.label}</label>)}<button className="admin-button" onClick={save}>保存权限</button></div>}</>}</div>}
