'use client'
import { useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'

export function CatalogEditor({kind,id}:{kind:'problem'|'point';id?:string}){
  const router=useRouter(); const [value,setValue]=useState<any>(kind==='problem'?{name:'',aliases:[],bodyAreaIds:[],description:'',needAsk:'',dangerNotice:'',methodLinks:[]}:{name:'',aliases:[],bodyAreaId:'',professionalLocation:'',everydayLocation:'',commonMistakes:'',notices:'',contentHtml:'',sourceTitle:'',sourceText:''}); const [csrf,setCsrf]=useState(''); const [loading,setLoading]=useState(Boolean(id)); const [saving,setSaving]=useState(false)
  useEffect(()=>{fetch('/api/admin/bootstrap').then(r=>r.json()).then(d=>setCsrf(d.user?.csrfToken||'')); if(id)fetch(kind==='problem'?'/api/admin/problems':'/api/admin/points').then(r=>r.json()).then(d=>{const row=(d[kind==='problem'?'problems':'points']||[]).find((x:any)=>x.id===id);if(row)setValue(row)}).finally(()=>setLoading(false))},[id,kind])
  const set=(k:string,v:any)=>setValue((x:any)=>({...x,[k]:v})); const save=async(e:any)=>{e.preventDefault();setSaving(true);const endpoint=kind==='problem'?'/api/admin/problems':'/api/admin/points';const r=await fetch(endpoint,{method:'POST',headers:{'content-type':'application/json','x-csrf-token':csrf},body:JSON.stringify({[kind]:value})});const d=await r.json();setSaving(false);if(!r.ok){alert(d.error||'保存失败');return}router.push(`/admin/${kind==='problem'?'problems':'points'}`)}
  if(loading)return <div className="admin-panel">正在读取资料…</div>
  return <div className="editor-layout"><form className="admin-panel admin-form content-editor" onSubmit={save}><div className="editor-head"><div><div className="eyebrow">基础数据库 / {kind==='problem'?'问题库':'穴位库'}</div><h1>{id?'编辑':'新建'}{kind==='problem'?'问题':'穴位'}</h1></div><div className="editor-actions"><button type="button" className="admin-button secondary" onClick={()=>router.back()}>取消</button><button className="admin-button" disabled={saving}>保存草稿</button></div></div><label>{kind==='problem'?'问题名称':'穴位名称'}<input required value={value.name||''} onChange={e=>set('name',e.target.value)}/></label><label>别名 / 用户说法<input value={(value.aliases||[]).join('、')} onChange={e=>set('aliases',e.target.value.split(/[、,，\n]/).map((x:string)=>x.trim()).filter(Boolean))}/></label>{kind==='problem'?<><label>关联部位<input value={(value.bodyAreaIds||[]).join('、')} onChange={e=>set('bodyAreaIds',e.target.value.split(/[、,，\n]/).map((x:string)=>x.trim()).filter(Boolean))}/></label><label>问题描述<textarea rows={4} value={value.description||''} onChange={e=>set('description',e.target.value)}/></label><label>需要追问<textarea rows={3} value={value.needAsk||''} onChange={e=>set('needAsk',e.target.value)}/></label><label>危险提示<textarea rows={3} value={value.dangerNotice||''} onChange={e=>set('dangerNotice',e.target.value)}/></label></>:<><label>标准身体部位<input required value={value.bodyAreaId||''} onChange={e=>set('bodyAreaId',e.target.value)}/></label><label>专业定位<textarea required rows={3} value={value.professionalLocation||''} onChange={e=>set('professionalLocation',e.target.value)}/></label><label>日常找法 / 经验取穴<textarea rows={3} value={value.everydayLocation||''} onChange={e=>set('everydayLocation',e.target.value)}/></label><label>常见误区与注意<textarea rows={3} value={value.commonMistakes||value.notices||''} onChange={e=>{set('commonMistakes',e.target.value);set('notices',e.target.value)}}/></label><label>正文图文<textarea className="rich-input" rows={10} value={value.contentHtml||''} onChange={e=>set('contentHtml',e.target.value)}/></label><div className="source-box"><h2>资料来源</h2><label>来源标题<input required value={value.sourceTitle||''} onChange={e=>set('sourceTitle',e.target.value)}/></label><label>来源原文 / 依据<textarea required rows={4} value={value.sourceText||''} onChange={e=>set('sourceText',e.target.value)}/></label></div></>}</form></div>
}
